### PR TITLE
Add r2v-quantize for quantizing a word embedding matrix

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Comment by danieldk** [comment]
@sebpuetz I have another commit, which topically fits in this PR. It stores the vector norms in the QuantizerArray as well. This is useful for subword embeddings, since their norms differ quite a bit. Let me know if you'd prefer to have this as a separate PR or add it to this PR.

After this PR and the aforementioned change, there are only API hiding + documentation changes, which probably do not have to go through a PR. Soon afterwards, we can cut the 0.5 release and convert all our embeddings (after perhaps an A3 meeting with possible feedback on the chunk format).

**Comment by sebpuetz** [comment]
Since I haven't started yet, just add it to this PR. I'll try to get to it soon

**Comment by danieldk** [comment]
ack, done

**Review by sebpuetz — APPROVED** [review]
This looks fine.
Do you plan to add conversion from quantized back to a full matrix representation? Could be useful to evaluate what kind of effects (de-)quantization on downstream tasks has

**Comment by danieldk** [comment]
> This looks fine.
> Do you plan to add conversion from quantized back to a full matrix representation? Could be useful to evaluate what kind of effects (de-)quantization on downstream tasks has

Didn't think of that (I was now just evaluating sticker with rust2vec), but that's a great idea for evaluating the embeddings with software where it may not be so easy.

**Pull request merged**
